### ISSUE TITLE
Mount Agent Alignment

### ISSUE THREAD

**Issue by ghulands** [indigo-astronomy/indigo_control_panel#1]
I am still new to indigo so not sure if I'm doing something wrong, but when I switched the mount agents alignment method, a new section was added to the control panel - "Delete alignment point". I then changed it to multi point and then another section was added - "Select alignment points".

![image](https://user-images.githubusercontent.com/127462/72130142-781e0680-332d-11ea-9697-1a20a1198626.png)

Since they are just empty sections, I'm not sure what I'm meant to do with them. Are they just unimplemented in the control panel / indigo dashboard at the moment?

**Comment by rumengb** [comment]
They will show up there when you add one. These are just like the alignment
points you define when you align your mount at startup with your hand
controller.

**Comment by ghulands** [comment]
Sorry, I'm a little confused on the process I would use to set everything up.

Where do I add them?

**Comment by rumengb** [comment]
hi,
those things you see in control panel are the so called properties - the
"guts" indigo, the building blocks that you can use to achieve your goal.
These are like both the routines and the variables in the computer
programming. Not everything you see in the control panel makes sense to
users. Consider Control Panel like a low level configuration of the system.
And the client software like Astro Telescope or Astro Imager should take
care of the sequence and purpose of using and setting the properties to
achieve certain result. So do not go too deep in to this things especially
when you are new to INDIGO :)

Rumen

**Comment by polakovic** [comment]
Alignment points are added by "sync" operation on the mount driver when alignment model is maintained by the driver (and not by e.g. hand controller). When no point is defined, you see empty set (a property without items). But even if control panel shows them, these properties are not intended for "manual" control.

**Comment by ghulands** [comment]
I went back and read [this](http://bb.cloudmakers.eu/viewtopic.php?f=7&t=417) thread and realized I misunderstood - I thought it was that the Dashboard was replacing the other individual apps so that was why i was trying everything through the dashboard. I've just grabbed the other apps and will get more comfortable with everything in there first. Thanks for the help.
