### ISSUE TITLE
specifying IP for a server causes weird server name display

### ISSUE THREAD

**Issue by ckuethe** [indigo-astronomy/indigo_control_panel#4]
Looks like server name is derived from splitting the hostname on `.` and using the 0th element... which isn't super helpful on an IP address. This is also present in indigo-astronomy/indigo_imager#4

![Screenshot_2021-11-07_14-47-37](https://user-images.githubusercontent.com/1131751/140664707-8f863d6a-a775-4bf2-81b3-acda2a0da5bd.png)

**Comment by rumengb** [comment]
fixed with commit: f87ae58dc3b3326b1ed12ff19fdaee2c2213b0b1
Will be available in the next release.
